# Completando essa sequência, tem-se: 2,10,12,16,17,18,19 e 200. Ou seja, o próximo número dessa sequência é 200 (duzentos). Visto que a  lógica da questão é justamente perceber que todos os números expostos obrigatoriamente começam coma letra 'd', por isso, o próximo número da sequência exposta será 200 (duzentos).

vetor_strings = [
    "zero",
    "um",
    "dois",
    "três",
    "quatro",
    "cinco",
    "seis",
    "sete",
    "oito",
    "nove",
    "dez",
    "onze",
    "doze",
    "treze",
    "quatorze",
    "quinze",
    "dezesseis",
    "dezessete",
    "dezoito",
    "dezenove",
    "vinte",
    "vinte e um",
    "vinte e dois",
    "vinte e três",
    "vinte e quatro",
    "vinte e cinco",
    "vinte e seis",
    "vinte e sete",
    "vinte e oito",
    "vinte e nove",
    "trinta",
    "trinta e um",
    "trinta e dois",
    "trinta e três",
    "trinta e quatro",
    "trinta e cinco",
    "trinta e seis",
    "trinta e sete",
    "trinta e oito",
    "trinta e nove",
    "quarenta",
    "quarenta e um",
    "quarenta e dois",
    "quarenta e três",
    "quarenta e quatro",
    "quarenta e cinco",
    "quarenta e seis",
    "quarenta e sete",
    "quarenta e oito",
    "quarenta e nove",
    "cinquenta",
    "cinquenta e um",
    "cinquenta e dois",
    "cinquenta e três",
    "cinquenta e quatro",
    "cinquenta e cinco",
    "cinquenta e seis",
    "cinquenta e sete",
    "cinquenta e oito",
    "cinquenta e nove",
    "sessenta",
    "sessenta e um",
    "sessenta e dois",
    "sessenta e três",
    "sessenta e quatro",
    "sessenta e cinco",
    "sessenta e seis",
    "sessenta e sete",
    "sessenta e oito",
    "sessenta e nove",
    "setenta",
    "setenta e um",
    "setenta e dois",
    "setenta e três",
    "setenta e quatro",
    "setenta e cinco",
    "setenta e seis",
    "setenta e sete",
    "setenta e oito",
    "setenta e nove",
    "oitenta",
    "oitenta e um",
    "oitenta e dois",
    "oitenta e três",
    "oitenta e quatro",
    "oitenta e cinco",
    "oitenta e seis",
    "oitenta e sete",
    "oitenta e oito",
    "oitenta e nove",
    "noventa",
    "noventa e um",
    "noventa e dois",
    "noventa e três",
    "noventa e quatro",
    "noventa e cinco",
    "noventa e seis",
    "noventa e sete",
    "noventa e oito",
    "noventa e nove",
    "cem",
    "cento e um",
    "cento e dois",
    "cento e três",
    "cento e quatro",
    "cento e cinco",
    "cento e seis",
    "cento e sete",
    "cento e oito",
    "cento e nove",
    "cento e dez",
    "cento e onze",
    "cento e doze",
    "cento e treze",
    "cento e quatorze",
    "cento e quinze",
    "cento e dezesseis",
    "cento e dezessete",
    "cento e dezoito",
    "cento e dezenove",
    "cento e vinte",
    "cento e vinte e um",
    "cento e vinte e dois",
    "cento e vinte e três",
    "cento e vinte e quatro",
    "cento e vinte e cinco",
    "cento e vinte e seis",
    "cento e vinte e sete",
    "cento e vinte e oito",
    "cento e vinte e nove",
    "cento e trinta",
    "cento e trinta e um",
    "cento e trinta e dois",
    "cento e trinta e três",
    "cento e trinta e quatro",
    "cento e trinta e cinco",
    "cento e trinta e seis",
    "cento e trinta e sete",
    "cento e trinta e oito",
    "cento e trinta e nove",
    "cento e quarenta",
    "cento e quarenta e um",
    "cento e quarenta e dois",
    "cento e quarenta e três",
    "cento e quarenta e quatro",
    "cento e quarenta e cinco",
    "cento e quarenta e seis",
    "cento e quarenta e sete",
    "cento e quarenta e oito",
    "cento e quarenta e nove",
    "cento e cinquenta",
    "cento e cinquenta e um",
    "cento e cinquenta e dois",
    "cento e cinquenta e três",
    "cento e cinquenta e quatro",
    "cento e cinquenta e cinco",
    "cento e cinquenta e seis",
    "cento e cinquenta e sete",
    "cento e cinquenta e oito",
    "cento e cinquenta e nove",
    "cento e sessenta",
    "cento e sessenta e um",
    "cento e sessenta e dois",
    "cento e sessenta e três",
    "cento e sessenta e quatro",
    "cento e sessenta e cinco",
    "cento e sessenta e seis",
    "cento e sessenta e sete",
    "cento e sessenta e oito",
    "cento e sessenta e nove",
    "cento e setenta",
    "cento e setenta e um",
    "cento e setenta e dois",
    "cento e setenta e três",
    "cento e setenta e quatro",
    "cento e setenta e cinco",
    "cento e setenta e seis",
    "cento e setenta e sete",
    "cento e setenta e oito",
    "cento e setenta e nove",
    "cento e oitenta",
    "cento e oitenta e um",
    "cento e oitenta e dois",
    "cento e oitenta e três",
    "cento e oitenta e quatro",
    "cento e oitenta e cinco",
    "cento e oitenta e seis",
    "cento e oitenta e sete",
    "cento e oitenta e oito",
    "cento e oitenta e nove",
    "cento e noventa",
    "cento e noventa e um",
    "cento e noventa e dois",
    "cento e noventa e três",
    "cento e noventa e quatro",
    "cento e noventa e cinco",
    "cento e noventa e seis",
    "cento e noventa e sete",
    "cento e noventa e oito",
    "cento e noventa e nove",
    "duzentos",
    "duzentos e um",
    "duzentos e dois",
    "duzentos e três",
]
l = []

for string in vetor_strings:
    if string[0] == "d":
        l.append(string)
print(l)
print("\n... => 2,10,12,16,17,18,19 e 200")
